#!/bin/bash

clear_project() {
    if [[ -n $ACTIVE_PROJECT ]]; then
        local PROJECT="$ACTIVE_PROJECT"
        __get_project "$PROJECT"

        if [[ -n $VIRTUALENV_INSTANCE ]]; then
            deactivate
            rm $VIRTUALENV_DIR/$VIRTUALENV_INSTANCE/Lib/site-packages/project.pth
        fi
        unset VIRTUALENV_INSTANCE

        [[ -n $PROJECT_PATH ]] && __remove_path "$PROJECT_PATH"
        unset PROJECT_PATH
        unset ADDITIONAL_VIMRCS
        unset ACTIVE_PROJECT
    fi
}

set_project() {
    if [[ -n $ACTIVE_PROJECT ]]; then
        clear_project
    fi

    local PROJECT="$1"
    __get_project "$PROJECT"


    if [[ -n $VIRTUALENV_INSTANCE ]]; then
        echo $PROJECT_PYTHONPATH > $VIRTUALENV_DIR/$VIRTUALENV_INSTANCE/Lib/site-packages/project.pth
        workon "$VIRTUALENV_INSTANCE"
    fi

    export PROJECT_PATH="$PROJECTS_DIR/$PROJECT/bin"
    [[ -n $PROJECT_PATH ]] && __add_path "$PROJECT_PATH"

    export ACTIVE_PROJECT="$PROJECT"
    export ADDITIONAL_VIMRCS=$( ls $PROJECTS_DIR/$PROJECT/.vim/*.vimrc)
}

__add_path() {
    PATH=$PATH:"$1"
}

__remove_path() {
    PATH=${PATH%:"$1"}
}

__get_project() {
    local PROJECT_CFG="$PROJECTS_DIR/$1/conf"
    if [[ -f $PROJECT_CFG ]]; then
        source $PROJECT_CFG
    else
        echo "Unknown project: $1"
    fi
}

__complete_project() {
    if [[ $COMP_CWORD == 1 ]]; then
        local CUR=${COMP_WORDS[COMP_CWORD]}
        local WORDS=$(find $PROJECTS_DIR -maxdepth 1 -mindepth 1 | xargs -l basename)
        COMPREPLY=( $( compgen -W "$WORDS" -- $CUR ) )
    fi
}
complete -F __complete_project set_project
